
services:
  node:
    image: "node"
    container_name: node
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "5665:5665"
    command: sh -c "npm i && npm start"
    volumes:
      - /var/www/ows:/app
    networks:
      - ows

networks:
  ows:
    external: true
